version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.16.1
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    networks:
      - spring-micro-net

  config-server:
    image: config-server:latest
    container_name: config-server
    build:
      context: ./config-server
    ports:
      - "8071:8071"
    depends_on:
      - vault
    networks:
      - spring-micro-net

networks:
  spring-micro-net:
    driver: bridge
