example.property= I AM DEV

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#``````````````````````````````````````````````````````JPA CONFIGS``````````````````````````````````````````````````````
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

spring.datasource.url = jdbc:postgresql://pg-1f2a7dcb-yomallearning-5abc.b.aivencloud.com:22078/ostock_dev?sslmode=require
spring.datasource.username = avnadmin
spring.datasource.password = ${DB_PWD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url = jdbc:postgresql://localhost:5432/ostock_dev
#spring.datasource.username = postgres
#spring.datasource.password = postgres